# Generated by Django 3.2.9 on 2022-01-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=200)),
                ('button_text', models.CharField(max_length=20)),
                ('button_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
