# Generated by Django 3.2.9 on 2022-01-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220123_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=200)),
                ('button_text', models.CharField(max_length=20)),
                ('button_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=200)),
                ('button_text', models.CharField(max_length=20)),
                ('button_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=200)),
                ('highlight', models.TextField(max_length=200)),
                ('button_text', models.CharField(max_length=20)),
                ('button_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('schedule', models.TextField(max_length=200)),
                ('button_text', models.CharField(max_length=20)),
                ('button_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(max_length=200)),
                ('button_text', models.CharField(max_length=20)),
                ('button_url', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('map_url', models.URLField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
