# Generated by Django 3.2.9 on 2022-01-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_box2_box3_course1_course2_home_local1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('map_url', models.URLField(max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local 2',
                'verbose_name_plural': 'Local 2',
            },
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='box1',
            options={'verbose_name': 'Box 1', 'verbose_name_plural': 'Box 1'},
        ),
        migrations.AlterModelOptions(
            name='box2',
            options={'verbose_name': 'Box 2', 'verbose_name_plural': 'Box 2'},
        ),
        migrations.AlterModelOptions(
            name='box3',
            options={'verbose_name': 'Box 3', 'verbose_name_plural': 'Box 3'},
        ),
        migrations.AlterModelOptions(
            name='course1',
            options={'verbose_name': 'Course 1', 'verbose_name_plural': 'Course 1'},
        ),
        migrations.AlterModelOptions(
            name='course2',
            options={'verbose_name': 'Course 2', 'verbose_name_plural': 'Course 2'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='local1',
            options={'verbose_name': 'Local 1', 'verbose_name_plural': 'Local 1'},
        ),
    ]
