# Generated by Django 3.2.9 on 2022-01-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_about_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box3',
            name='button_text',
        ),
        migrations.RemoveField(
            model_name='box3',
            name='button_url',
        ),
    ]
