# Generated by Django 3.2.9 on 2022-01-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220123_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local1',
            name='map_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='local2',
            name='map_url',
            field=models.URLField(),
        ),
    ]
