# Generated by Django 3.2.9 on 2022-01-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
